name: Build-Packages
on:
  pull_request:
    branches: [ master ]
    paths:
    - 'AutoWeb/**'
  workflow_dispatch:
jobs:
  verify-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Update Version
      uses: Amadevus/pwsh-script@v2.0.1
      id: update-version
      with:
        script: |
          $file = Get-ChildItem -Path "$($github.workspace)" -Filter "*AutoWeb.csproj" -Recurse
          if($null -eq $file){
              throw "Failed to find AutoWeb.csproj"
          }
          $csproj = [xml](Get-Content $file.FullName)

          $d = [System.TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::Now,"Pacific Standard Time") | Get-Date -Hour 0 -Minute 0 -Second 0
          $diff = ((Get-Date) - $d)
          $seconds = [Math]::Round($diff.TotalSeconds / 2)
          $ver = "$($d.ToString('yyyy.MM.dd')).$seconds"

          $csproj.SelectSingleNode("//Version").InnerText = $ver
          Write-ActionInfo "Version: $ver"
          $csproj.Save($file.FullName)
          return 0
      continue-on-error: false
    - name: Build Debug
      run: dotnet build --no-restore
    - name: Run Tests
      run: dotnet test --no-build --verbosity normal
    - name: Build Release
      run: dotnet build --no-restore --configuration Release
    - name: Pack
      run: dotnet pack --configuration Release
    - name: Create Artifact
      uses:  actions/upload-artifact@v2.2.2
      with:
        name: AutoWeb
        if-no-files-found: error
        path: './AutoWeb/bin/Release/*'
        
  # Deploy to GitHub Nuget
  nuget-package-github:
    runs-on: windows-latest
    needs: verify-build
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Download Artifact
      id: download
      uses:  actions/download-artifact@v2.0.8
      with:
        name: AutoWeb
    - name: 'Echo download path'
      run: echo ${{steps.download.outputs.download-path}}
    - name: Publish Nuget to GitHub registry
      run: dotnet nuget push "${{steps.download.outputs.download-path}}\*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/lzinga/index.json --skip-duplicate --no-symbols true
      
  # Deploy to Nuget.org
  nuget-package-deploy:
    runs-on: windows-latest
    needs: verify-build
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Download Artifact
      id: download
      uses:  actions/download-artifact@v2.0.8
      with:
        name: AutoWeb
    - name: 'Echo download path'
      run: echo ${{steps.download.outputs.download-path}}
    - name: Publish to Nuget registry
      run: dotnet nuget push "${{steps.download.outputs.download-path}}\*.nupkg" --api-key ${{ secrets.NUGETAPI }} --source https://api.nuget.org/v3/index.json